name: Build runner app

on:
  workflow_call:

jobs:
  setups:
    name: builder
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node: [18.x]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/node_modules/
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            - cache-node-modules-

      - name: Build dist
        run: |
          yarn build

      - name: Upload Dist Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
