name: Pull Request Checks

on:
  pull_request:
    branches: [main, develop, release/*]

jobs:
  setups:
    name: Setup packages
    uses: ./.github/workflows/setup-packages-job.yml

  unit-test:
    name: Run lint
    needs: [setups]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'yarn'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/node_modules/
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            - cache-node-modules-

      - name: Run unit tests
        run: yarn lint

  build:
    name: Build dist
    needs: [setups]
    uses: ./.github/workflows/builder-job.yml
